### ISSUE TITLE
magicbot: Running teleop code during autonomous

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib-utilities#130]
We should have an official prescribed way to do this. Ideas?

**Comment by auscompgeek** [comment]
Current (terrifying) workaround:

```python
class Robot(magicbot.MagicRobot):
  def createObjects(self):
    self.robot = self
```

```python
class TeleopSandstorm:
  MODE_NAME = "Teleop"

  robot: magicbot.MagicRobot

  def on_enable(self): pass
  def on_disable(self): pass

  def on_iteration(self, _time_elapsed):
    self.robot.teleopPeriodic()
```

**Comment by ArchdukeTim** [comment]
What if you want to run an autonomous, but interrupt the state machine or whatever when someone takes over the controls?

**Comment by virtuald** [comment]
It seems that the autonomous should just be an automation that could be triggered from teleop in that case?
