### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib-utilities#163]
https://gist.github.com/CrispyBacon1999/c495be4015993f88e0410cd93826821b

**Comment by auscompgeek** [comment]
I can't reproduce this. @CrispyBacon1999 is this still an issue for you?

**Comment by CrispyBacon1999** [comment]
Seems like this is fixed too, possibly related to https://github.com/robotpy/robotpy-wpilib/issues/649
