### ISSUE TITLE
Cannot import commandbased

### ISSUE THREAD

**Issue by adam-mcdaniel** [robotpy/robotpy-wpilib-utilities#164]
Going based off of the example code, I've been trying to import `CommandBasedRobot` from `commandbased`. Its not working because it cannot import `wpilib.command`.
![command](https://user-images.githubusercontent.com/28228031/74591978-d1dbb580-4fea-11ea-8d9e-2f44b9398277.PNG)

**Comment by virtuald** [comment]
Commands installation is separate this year. Honestly, we should move the commandbased stuff over to that module, because if we ever get commands v2 working it'll probably need a different commandbased base.

https://robotpy.readthedocs.io/en/stable/install/commands.html
