### ISSUE TITLE
StatefulAutonomous: next_state should accept functions as arguments

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib-utilities#17]
Seems like a reasonable thing to do.

**Comment by Twinters007** [comment]
I don't think you can do this with timed states. You can do it with next_state as a function, but because python doesn't load all the methods first you can't declare the next state as a future function

**Comment by virtuald** [comment]
`self.next_state(self.foo)` would work.

**Comment by Twinters007** [comment]
ok I think when I was testing I was trying to put the method in the decorator, which doesn't work.

**Comment by virtuald** [comment]
That's correct for the decorator, but not when next_state is called by code at runtime.

**Comment by virtuald** [comment]
Fixed in #37
