### ISSUE TITLE
magicbot: use time.monotonic for state machines

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib-utilities#24]
Might want to use this for PreciseDelay also, which needs to be revisited.

**Comment by Twinters007** [comment]
It'll be harder to run tests because you can't fake time.monotonic

**Comment by virtuald** [comment]
Why not?

**Comment by Twinters007** [comment]
https://docs.python.org/3/library/time.html#time.CLOCK_MONOTONIC

If you use the monotonic clock you can't set it, so how do you simulate time passing?

**Comment by auscompgeek** [comment]
The same way we simulate time passing now.

**Comment by Twinters007** [comment]
But now we use the wpitime...I figured it edited the time gotten by getFPGATimestamp

**Comment by Twinters007** [comment]
hal.HALIsSimulation is a wonderful thing I think

**Comment by Twinters007** [comment]
close
