### ISSUE TITLE
NavX getRate() not working

### ISSUE THREAD

**Issue by czhao39** [robotpy/robotpy-wpilib-utilities#50]
It seems that `getRate()` stopped working due to an update within the past two weeks. Now when the NavX is not rotating, `getRate()` returns 360 degrees per second. However, `getAngle()` still seems to work fine. Unfortunately, I did not have enough time today to play with the NavX to see if the offset of 360 degrees per second was consistent. In case it's relevant, I'm using spi.

**Comment by auscompgeek** [comment]
The NavX driver was updated in 1f4fc57 for this year. Having a look at [continuousangletracker.py](/robotpy/robotpy-wpilib-utilities/blame/1f4fc57/robotpy_ext/common_drivers/navx/continuousangletracker.py#L104) and the upstream [ContinuousAngleTracker.java](/kauailabs/navxmxp/blob/c5e3a8a9b642/roborio/java/navx_frc/src/com/kauailabs/navx/frc/ContinuousAngleTracker.java#L128), it looks like someone somehow forgot to include a condition.

**Comment by czhao39** [comment]
Oh yeah, that would do it. Thanks!

**Comment by virtuald** [comment]
Sorry about that, I'll push a new release momentarily.
