### ISSUE TITLE
magicbot: Use Python 3.6 variable annotations to mark objects to be injected

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-wpilib-utilities#57]
Idea for the future (since this would require users to use Python 3.6). Instead of having components that look like this:

```python
class Component:
  sd = NetworkTable

  def execute(self):
    self.sd.putValue('foo', 'bar')
```

have something that looks like this instead:
```python
class Component:
  sd: NetworkTable

  def execute(self):
    self.sd.putValue('foo', 'bar')
```
(i.e. change the `=` to `:`)

This has the added advantage of not confusing tooling such as pylint, and would look less confusing to those new to magicbot.

**Comment by Twinters007** [comment]
I second this.
