### ISSUE TITLE
Update navX library for 2018

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-wpilib-utilities#82]
There's been a number of changes in WPILib that have necessitated changes to the navX library. kauailabs/navxmxp@73aa4ea84010 in particular sticks out to me.

@virtuald I was taking a brief look at this earlier, and I noticed the commit referenced in the git-source-track line in ahrs.py is from 2016. Judging by the code, I'm guessing that wasn't intended?

**Comment by virtuald** [comment]
I may have forgotten to update the git source-track line last year -- though, if I recall correctly, there were not a ton of changes.

**Comment by auscompgeek** [comment]
The weird part is that the line _was_ updated. It's just a commit from a significant amount of time before the line was updated.

**Comment by virtuald** [comment]
It's possible that I updated it and neglected to update git-source-track. Sounds like the sort of thing I might do.
