### ISSUE TITLE
magicbot should not subclass SampleRobot

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-wpilib-utilities#86]
Let's avoid reinventing the wheel.

**Comment by twinters007** [comment]
should we make this happen in 2018? Right now, because it subclasses sample, DeprecationWarnings are getting thrown in tests

**Comment by virtuald** [comment]
This seems like a good idea.

**Comment by auscompgeek** [comment]
I think we should rewrite the auto framework to instead run single iterations at a time and let the robot class deal with timing. Maybe keep around a version that keeps using PreciseDelay if for some reason a team wants to keep using IterativeRobot but prefers a stable timing for autonomous.

Also on the SampleRobot front, maybe we should un-deprecate SampleRobot. WPILib's intent there was to make a warning show up in IDEs and at compile time. Showing some other warning, preferably one that can be programmatically ignored if teams so wish, could happen in simulation too. I would prefer such a warning to not show up in DS logs though.

**Comment by auscompgeek** [comment]
Upstream have removed SampleRobot altogether (the replacement being to subclass RobotBase directly), so this should happen ASAP. Should be relatively straightforward.
